server.port=8084
# Jeśli system ma zmienną SPRING_DATASOURCE_URL (tak będzie w Dockerze na AWS), użyje jej.
# Jeśli jej nie ma (bo odpalasz aplikację prosto z Intellij/Eclipse na laptopie), użyje adresu localhost.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/analyzer_db}

# To samo robimy dla użytkownika i hasła – na laptopie podajesz swoje lokalne dane do PG
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer